# Copyright (c) 2019 com.vesoft inc. All rights reserved.
#
# This source code is licensed under Apache 2.0 License,
# attached with Common Clause Condition 1.0, found in the LICENSES directory.

language: java

jdk:
  - openjdk8

install: mvn install -Dgpg.skip