name: release

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Install nebula-graph
        run: |
          mkdir tmp
          pushd tmp
          git clone https://github.com/vesoft-inc/nebula-docker-compose.git
          pushd nebula-docker-compose/
          cp ../../client/src/test/resources/docker-compose.yaml .
          docker-compose up -d
          sleep 30
          docker-compose ps
          popd
          popd

      - name: Install nebula-graph with CA SSL
        run: |
          pushd tmp
          mkdir ca
          pushd ca
          cp -r ../../client/src/test/resources/ssl .
          cp ../../client/src/test/resources/docker-compose-casigned.yaml .
          docker-compose -f docker-compose-casigned.yaml up -d
          sleep 30
          docker-compose -f docker-compose-casigned.yaml ps
          popd
          popd

      - name: Install nebula-graph with Self SSL
        run: |
          pushd tmp
          mkdir self
          pushd self
          cp -r ../../client/src/test/resources/ssl .
          cp ../../client/src/test/resources/docker-compose-selfsigned.yaml .
          docker-compose -f docker-compose-selfsigned.yaml up -d
          sleep 30
          docker-compose -f docker-compose-selfsigned.yaml ps
          popd
          popd

      - name: Deploy Release to Maven package
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ secrets.JAVA_GPG_PRIVATE_KEY }}
          gpg_passphrase: ""
          nexus_username: ${{ secrets.OSSRH_USERNAME }}
          nexus_password: ${{ secrets.OSSRH_TOKEN }}
